
import "./globals.css";
import { AuthProvider } from "./Providers";

export const metadata = {
  title: "Auth App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          
          <div>
          <AuthProvider>{children}</AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
